### PR TITLE
[Breaking Change]: Remove save file func

### PR DESCRIPTION
**Pull request by Milind220**
This PR will address the breaking change of removing the save to file functionality that Ozone currently offers.

### CODE REVIEW

**Comment by Milind220** [comment]
Work that needs to be done:

- [ ] Modify tests to work with lack of save file feature.

**Comment by Milind220** [comment]
@lahdjirayhan I believe this PR is complete :) I'll check again tomorrow

**Review by lahdjirayhan — COMMENTED** [review]
The presence of `*` will force users to give `city` or `city_id` by name. Giving arguments by position will raise an error.
See 

 In my opinion, this avoids mixing up whether the user is giving a `city` or `city_id`.

But I think getting rid of it is also fine since the arguments are checked immediately.

**Comment by lahdjirayhan** [comment]
@Milind220

Looks good to me!

Could you also please update the README because I think there's an example that still shows `data_format` argument being used.

**Comment by Milind220** [comment]
@lahdjirayhan Hey, any idea why the linter checks might be failing?

**Comment by Milind220** [comment]
Okay I'm trying to solve some merge conflicts lol - excuse me if this gets a little messy.

**Pull request merged**
