### PR TITLE
CI/CD: Create GitHub action to assign issues to contributors if they comment on an issue saying "Hold my beer, I got this"

### PR DESCRIPTION
**Pull request by kowshik-noor**
I added a workflow that will assign an issue to any contributor if they comment on an issue saying, "Hold my beer, I got this." I did this by linking the workflow to [a slightly modified version of Brian Douglas's action.](https://github.com/kowshik-noor/take-action/tree/beer-comment)

### CODE REVIEW

**Comment by Milind220** [comment]
@kowshik-noor  Hey, Thanks for your contribution!

Does this GitHub Action require a private token in order to function?

**Comment by kowshik-noor** [comment]
@Milind220 A private token is not required. GitHub will automatically generate a token when this action runs. The token will expire when the action is finished. 

More info can be found [here](https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp).

**Comment by Milind220** [comment]
@kowshik-noor That makes sense! Thanks a lot.

**Review by Milind220 — APPROVED** [review]
Great stuff, excited to try it out

**Pull request merged**
