### PR TITLE
feat: Add method to get AQI forecasts

### LINKED ISSUE #36: Add method to show air quality forecast information. The API actually returns this info, but we currently ignore it.
The WAQI API [documentation](https://aqicn.org/json-api/doc/) mentions how the JSON object that is retuned contains 'forecast' data as well. This is basically the 7 day forecast for 4 parameters: pm25, pm10, o3, and uvi.

Create a method that takes in a city and fetches the forecast data for it. Allow users to enter a list of the specific parameters they want, and get all by default. 

You can refer to the `get_city_air` method while making this. The implementation would be quite similar.

### PR DESCRIPTION
**Pull request by lahdjirayhan**
This PR tries to fix #36.

### CODE REVIEW

**Comment by lahdjirayhan** [comment]
@Milind220 This PR needs some refactoring first. The code was dirty because I intended it for demonstration only. It contains a direct copy-pasted logic as I've mentioned here:

https://github.com/lahdjirayhan/Ozone/blob/5e122d2eb632490e3cc3ca83e5343f60541e0ef5/src/ozone/ozone.py#L630-L635

**Comment by lahdjirayhan** [comment]
@Milind220 Now ready for review and merge. I think the methods are better organized now.

On the other hand ...

... I was feeling really uncomfortable refactoring the codebase. If only we have unit tests to run every now and then to assure us we're not breaking anything... (and fix #8)

**Comment by Milind220** [comment]
@lahdjirayhan Yeah, we really need to set up unit tests...

I've sent a reminder in the #8 conversation. If there's no responses in a day, we can reassign that issue to someone else

**Review by Milind220 — APPROVED** [review]
Great stuff! merging now :)

**Pull request merged**
