### PR TITLE
Added Showcase Gifs to README.md

### PR DESCRIPTION
**Pull request by tariksouabny**

### CODE REVIEW

**Review by Milind220 — CHANGES_REQUESTED** [review]
Noticed that you've named a variable as 'token'.  Considering that a user may get confused between their API token and this variable token, this may not be the best name.

Can you change the name of 'token' to 'o3' 

considering that ooo.Ozone() would return an Ozone object this makes more sense.

**Review by Milind220 — CHANGES_REQUESTED** [review]
for the `get_multiple_city_data` method could you add at least one other city's name in the array that you pass in? It would make the usage of the method clearer.

**Comment by Milind220** [comment]
@tariksouabny Hey! If you could make these two small changes, I'll merge your PR right away :)

**Comment by tariksouabny** [comment]
I updated the `token` variable to be `o3` and updated the `get_multiple_city_air()` method to also get Beijing. I also updated these changes in the README.md.

**Review by Milind220 — APPROVED** [review]
Perfect! that's sure to help new users understand how to use the code better.

**Pull request merged**
