### PR TITLE
docs: Add semantic versioning and branching model sections

### PR DESCRIPTION
**Pull request by kristinamancini**
In the contributing file, I added 'Semantic Versioning System' and 'Github Branching Model' sections and short descriptions at the bottom of the file. I also added those two sections in the table of contents.

### CODE REVIEW

**Review by Sam-damn — CHANGES_REQUESTED** [review]
@kristinamancini Great work! i really love the short descriptions u provided and thank you for adding them into the the table of contents :)
i would like to request a small little change however, the links that are referred to should ideally be links to our discussions, since in the discussions we offer a little bit extra information. here are the links if u can add them in place of the ones u already have that would be great!

Github Branching Model url: https://github.com/Milind220/Ozone/discussions/24
Semantic Versioning System url: https://github.com/Milind220/Ozone/discussions/26

Aditionally i think it would be better if the Semantic Versioning System section is moved to the bottom of the README.md below the 'Contributing and submitting Pull requests' instead of the contributing.md

**Comment by kristinamancini** [comment]
Got it, I believe I fixed it.

**Review by Sam-damn — APPROVED** [review]

**Comment by Sam-damn** [comment]
Thank you very much @kristinamancini  :)

**Comment by Milind220** [comment]
@kristinamancini Feel free to take a look at the other issues we have open, got some interesting ones there. We'd love to guide you through the process of making code contributions to Ozone!

**Comment by kristinamancini** [comment]
I'll check out the other issues, thank you for allowing me to contribute!

**Pull request merged**
