### PR TITLE
feat: Add capability to scrape historical data

### PR DESCRIPTION
**Pull request by Sam-damn**
i would like to explain few points regarding some choices that i made:

1.  The reason i implemented the scraping code in a different model "scraping" is to not clutter the Ozone package main model which should be left for the main functionality of the API itself, i did however add the get_historical_data method to the Ozone class because it is part of the API now (by API i mean the interface that we provide to consumers of the package and not the website API).  Also adding a model specifically for scraping will prove handy in future in case any further scraping features need to be implemented.
2. i added a basic class (AirDataHistory) which encapsulates the data for a single table scraped by the scraper, this class offers useful functionality like for example getting data at certain date or between two dates (the latter will be added shortly), which can be useful if the user is only interested in data across a certain time span
3. The AirDataHistory represents the table data scraped for a specific type of gas, ex: PM2.5 or O3. hence we will have multiple instances of this class for each gas 
4.  i made the selenium web-driver instance global as in model wise, so it can be used by other scrapers as it is needed.

i tested the code a lot on my machine with no errors, however because we are using selenium i reckon we might come across some bugs if the web browser versions differs,  so it needs to be tested before we merge this pull request.

### CODE REVIEW

**Comment by Sam-damn** [comment]
I forgot to Mention, that the scraping process takes a while , I added few print debug statements to get an idea where the scraping process is at.

**Comment by Milind220** [comment]
> 1. The reason i implemented the scraping code in a different model "scraping" is to not clutter the Ozone package main model which should be left for the main functionality of the API itself, i did however add the get_historical_data method to the Ozone class because it is part of the API now (by API i mean the interface that we provide to consumers of the package and not the website API).  Also adding a model specifically for scraping will prove handy in future in case any further scraping features need to be implemented.

^ This makes perfect sense. Good thinking! 

> 2. i added a basic class (AirDataHistory) which encapsulates the data for a single table scraped by the scraper, this class offers useful functionality like for example getting data at certain date or between two dates (the latter will be added shortly), which can be useful if the user is only interested in data across a certain time span

Awesome stuff! Super excited for the date range feature addition! 
> 3. The AirDataHistory represents the table data scraped for a specific type of gas, ex: PM2.5 or O3. hence we will have multiple instances of this class for each gas
> 4. i made the selenium web-driver instance global as in model wise, so it can be used by other scrapers as it is needed.

Alright! Sounds like a really solid way of implementing this feature :)
> i tested the code a lot on my machine with no errors, however because we are using selenium i reckon we might come across some bugs if the web browser versions differs, so it needs to be tested before we merge this pull request.

Yeah definitely will have to test it thoroughly

**Comment by Milind220** [comment]
> I forgot to Mention, that the scraping process takes a while , I added few print debug statements to get an idea where the scraping process is at.

That makes sense considering that it's selenium. We can add a note of this in the documentation to make users aware of this too! Shouldn't be a problem at all

**Comment by Milind220** [comment]
@Sam-damn Totally awesome work with this feature! I'll merge this into the hist-data branch and test it out! Amazing! 

At this pace, you could become a co-maintainer of Ozone! I certainly could use the help :)

**Comment by Sam-damn** [comment]
Thanks! @Milind220 , i would love to be a co-maintainer of this awesome repository!

**Comment by Milind220** [comment]
@Sam-damn Hey, if you're actually interested, I'd love that too! Check your inbox :)

**Comment by Sam-damn** [comment]
@Milind220  indeed, i have sent you an email :)

**Pull request merged**
